apiVersion: apps/v1
kind: Deployment
metadata:
  name: anti-spam-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: anti-spam-api
  template:
    metadata:
      labels:
        app: anti-spam-api
    spec:
      containers:
        - name: anti-spam-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: OPENAI_API_KEY
              value: "{{ .Values.env.OPENAI_API_KEY }}"
          resources:
{{ toYaml .Values.resources | indent 12 }}
