apiVersion: v1
kind: Service
metadata:
  name: anti-spam-api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
    app: anti-spam-api
